version: '3.8'
services:
  postgres:
    image: postgres:15
    env_file: 
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  node:
    container_name: api
    image: node:20
    depends_on:
      postgres:
        condition: service_healthy
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run migration:run && npm run build && npm run start:prod"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
    networks:
      - app-network
    ports:
      - "4000:3000"
networks:
  app-network:
    driver: bridge